# Generated by Django 2.1.3 on 2019-04-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190406_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
