# Generated by Django 2.2 on 2019-04-14 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190408_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['topic_text']},
        ),
    ]
