# Generated by Django 2.2 on 2020-05-11 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190414_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=25)),
                ('job_desc', models.TextField()),
                ('trigger', models.IntegerField(default=0)),
                ('job_status', models.IntegerField(default=0)),
                ('job_msg', models.TextField(blank=True)),
                ('dte_last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
